#激活哪一个环境的配置文件
#公共配置
server:
  port: 8080

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/pethome?serverTimezone=Asia/Shanghai
    username: root
    password: zd159753
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句

